name: Azure ARM Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with Azure CLI
      run: |
        az login --allow-no-subscriptions --service-principal \
          --username "${{ secrets.AZURE_CLIENT_ID }}" \
          --password "${{ secrets.AZURE_CLIENT_SECRET }}" \
          --tenant "${{ secrets.AZURE_TENANT_ID }}"

    - name: Set Azure Account
      run: |
        az cloud set --name AzureCloud
        az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

    - name: Deploy ARM Template
      run: |
        az deployment group create \
          --resource-group rg-bot-deployment-test \
          --template-file SemanticKernelAgent.AgentAP/ArmTemplates/final.json \
          --parameters SemanticKernelAgent.AgentAP/ArmTemplates/parameters.json \
          --mode Incremental
