name: Deploy ARM Template

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Log in to Azure using a service principal
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        

    # Step 3: Deploy the ARM template
    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        scope: resourceGroup
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: rg-bot-deployment-test
        template: SemanticKernelAgent.AgentAPI/ArmTemplates/final.json
        parameters: SemanticKernelAgent.AgentAPI/ArmTemplates/parameters.json
